meshtastic:
  host: "192.168.0.172"
  active_timeout: 7200

openhab:
  url: "http://192.168.0.9:8080"
  timeout: 5
  command_item: Meshtastic_Command
  response_item: Meshtastic_Response
  sender_item: Meshtastic_Sender
  client_item: Meshtastic_Client
  message_item: Meshtastic_Message
  send_item: Meshtastic_Send
  nodes_item: Meshtastic_Nodes
  active_nodes_item: Meshtastic_ActiveNodes
  active_nodes_list: Meshtastic_ActiveNodeList
  last_heard_age_item: Meshtastic_LastHeardAge
  last_heard_node_item: Meshtastic_LastHeardNode

logging:
  level: INFO
  technical_log: logs/ohmeshbridge.log
  audit_log: logs/audit.log
  max_size_mb: 5
  backups: 10
  
security:
  private_only: true

users:
  "!6984de04":
    name: Steno
    role: admin

  "!1ba13494":
    name: Steno2
    role: admin

